function MapCells() {
  return (
    <>
      <table>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
        <tr>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
          <th>
            <button>.</button>
          </th>
        </tr>
      </table>
    </>
  )
}

export default MapCells;