function MapCells() {
  return (
    <>
      <table>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>
        <tr>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
          <th>
            .
          </th>
        </tr>

      </table>
    </>
  )
}

export default MapCells;